name: Trigger auto deployment for zatrust

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/zatrust-AutoDeployTrigger-472fe7a2-8884-4b06-a5f1-ed74d14e7016.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ZATRUST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ZATRUST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ZATRUST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: containerregisterysa.azurecr.io
          registryUsername: ${{ secrets.ZATRUST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ZATRUST_REGISTRY_PASSWORD }}
          containerAppName: zatrust
          resourceGroup: rg_container-app
          imageToBuild: containerregisterysa.azurecr.io/zatrust:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


